import type { Metadata } from "next";
import { Red_Hat_Display } from "next/font/google";
import "./globals.scss";

const redHatDisplay = Red_Hat_Display({
  variable: "--font-red-hat-display",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "SOTR",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={`${redHatDisplay.variable}`}>{children}</body>
    </html>
  );
}
